# /cashier_app/ui/main_ui.py
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1382, 745)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    font-family:Segoe UI;\n"
"    color:#222222;\n"
"    background:rgba(250, 249, 248, 1);\n"
"    font-weight:bold;\n"
"    font-size:15px;\n"
"}\n"
"\n"
"/* #58151c : coffee, rgba(39,30,22,1), rgba(40, 29, 21, 1) */\n"
"#header{\n"
"    background-color:#fff;\n"
"    border-bottom:1px solid #dcdcdc;\n"
"    box-shadow:0px 4px 8px rgba(40, 29, 21, 1);\n"
"}\n"
"\n"
"#emptyOrder,#scrollContentWidget,#categoryWidget,#ctBodyFrame,#ctBodyFrame2,#ctFrame1,#ctFrame2,#ctFrame3,#ctFrame4,#ctFrame5,#ctFrame6,#ctFrame7,#ctFrame8,#ctFrame9,#categoryFrame,#categoryFrame1,#categoryFrame2,#categoryFrameLabel,#categoryFrameButton{\n"
"    background:#fff;\n"
"    border:none;\n"
"}\n"
"\n"
"#homeIcon,#notifIcon,#cartIcon,#notiFrame,#homeFrame{\n"
"    background-color:#fff;\n"
"    border:none;\n"
"    qproperty-iconSize:30px 30px;\n"
"}\n"
"\n"
"#searchColumn,#searchIcon{\n"
"    border-radius:10px;\n"
"    background-color:rgba(250, 249, 248, 1);\n"
"    font-size:12px;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"#searchFrame{\n"
"    border-radius:10px;\n"
"    background-color:rgba(250, 249, 248, 1);\n"
"    font-size:11px;\n"
"    font-weight:bold;\n"
"    border:1px solid #e0e0e0;\n"
"}\n"
"\n"
"#category1,#category2,#category3,#category4,#category5,#category6,#category7,#category8{\n"
"    background-color:#f9f9f9;\n"
"    border-radius:5px;\n"
"    border:1px solid #dcdcdc;\n"
"    font-weight:bold;\n"
"    padding:24px;\n"
"    box-shadow:0px 4px 8px rgba(0,0,0,0.1);\n"
"    min-width: 250px;\n"
"    min-height: 165px;\n"
"    max-width: 250px;\n"
"    max-height: 165px;\n"
"    qproperty-iconSize:300px 300px;\n"
"}\n"
"\n"
"\n"
"#category1:hover,#category2:hover,#category3:hover,#category4:hover,#category5:hover,#category6:hover,#category7:hover,#category8:hover{\n"
"    background-color:#e0e0e0;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"#category1:pressed,#category2:pressed,#category3:pressed,#category4:pressed,#category5:pressed,#category6:pressed,#category7:pressed,#category8:pressed{\n"
"    background-color:#c8c8c8c8;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"#categoryLabel1,#categoryLabel2,#categoryLabel3,#categoryLabel4,#categoryLabel7,#categoryLabel8,#categoryLabel9{\n"
"    box-shadow:0px 4px 8px rgba(0,0,0,0.1);\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(-1, 9, -1, 9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.homeFrame = QtWidgets.QFrame(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeFrame.sizePolicy().hasHeightForWidth())
        self.homeFrame.setSizePolicy(sizePolicy)
        self.homeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.homeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.homeFrame.setObjectName("homeFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.homeFrame)
        self.verticalLayout_2.setContentsMargins(9, 9, 0, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.homeIcon = QtWidgets.QToolButton(self.homeFrame)
        self.homeIcon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/icon/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeIcon.setIcon(icon)
        self.homeIcon.setObjectName("homeIcon")
        self.verticalLayout_2.addWidget(self.homeIcon)
        self.horizontalLayout_2.addWidget(self.homeFrame)
        self.searchFrame = QtWidgets.QFrame(self.header)
        self.searchFrame.setMaximumSize(QtCore.QSize(16777215, 35))
        self.searchFrame.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.searchFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.searchFrame)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchIcon = QtWidgets.QLabel(self.searchFrame)
        self.searchIcon.setMaximumSize(QtCore.QSize(30, 30))
        self.searchIcon.setText("")
        self.searchIcon.setPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/icon/iconSearch.png"))
        self.searchIcon.setScaledContents(True)
        self.searchIcon.setObjectName("searchIcon")
        self.horizontalLayout_3.addWidget(self.searchIcon)
        self.searchColumn = QtWidgets.QLineEdit(self.searchFrame)
        self.searchColumn.setInputMask("")
        self.searchColumn.setText("")
        self.searchColumn.setDragEnabled(False)
        self.searchColumn.setClearButtonEnabled(False)
        self.searchColumn.setObjectName("searchColumn")
        self.horizontalLayout_3.addWidget(self.searchColumn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.searchFrame)
        self.notiFrame = QtWidgets.QFrame(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notiFrame.sizePolicy().hasHeightForWidth())
        self.notiFrame.setSizePolicy(sizePolicy)
        self.notiFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notiFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notiFrame.setObjectName("notiFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.notiFrame)
        self.horizontalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.notifIcon = QtWidgets.QToolButton(self.notiFrame)
        self.notifIcon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/icon/notification.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notifIcon.setIcon(icon1)
        self.notifIcon.setObjectName("notifIcon")
        self.horizontalLayout_4.addWidget(self.notifIcon)
        self.cartIcon = QtWidgets.QToolButton(self.notiFrame)
        self.cartIcon.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/icon/shopping-cart.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cartIcon.setIcon(icon2)
        self.cartIcon.setObjectName("cartIcon")
        self.horizontalLayout_4.addWidget(self.cartIcon)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.notiFrame)
        self.verticalLayout.addWidget(self.header, 0, QtCore.Qt.AlignTop)
        self.mainBody = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBody.sizePolicy().hasHeightForWidth())
        self.mainBody.setSizePolicy(sizePolicy)
        self.mainBody.setObjectName("mainBody")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.mainBody)
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.categoryWidget = QtWidgets.QWidget(self.mainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoryWidget.sizePolicy().hasHeightForWidth())
        self.categoryWidget.setSizePolicy(sizePolicy)
        self.categoryWidget.setObjectName("categoryWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.categoryWidget)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.categoryWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContentWidget = QtWidgets.QWidget()
        self.scrollContentWidget.setGeometry(QtCore.QRect(0, 0, 1330, 644))
        self.scrollContentWidget.setObjectName("scrollContentWidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollContentWidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.categoryFrame = QtWidgets.QFrame(self.scrollContentWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoryFrame.sizePolicy().hasHeightForWidth())
        self.categoryFrame.setSizePolicy(sizePolicy)
        self.categoryFrame.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.categoryFrame.setFont(font)
        self.categoryFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.categoryFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.categoryFrame.setObjectName("categoryFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.categoryFrame)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.categoryFrame1 = QtWidgets.QFrame(self.categoryFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoryFrame1.sizePolicy().hasHeightForWidth())
        self.categoryFrame1.setSizePolicy(sizePolicy)
        self.categoryFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.categoryFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.categoryFrame1.setObjectName("categoryFrame1")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.categoryFrame1)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.categoryFrameLabel = QtWidgets.QLabel(self.categoryFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoryFrameLabel.sizePolicy().hasHeightForWidth())
        self.categoryFrameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.categoryFrameLabel.setFont(font)
        self.categoryFrameLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard)
        self.categoryFrameLabel.setObjectName("categoryFrameLabel")
        self.horizontalLayout_10.addWidget(self.categoryFrameLabel)
        self.horizontalLayout_9.addWidget(self.categoryFrame1)
        self.categoryFrame2 = QtWidgets.QFrame(self.categoryFrame)
        self.categoryFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.categoryFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.categoryFrame2.setObjectName("categoryFrame2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.categoryFrame2)
        self.horizontalLayout_11.setContentsMargins(9, -1, 0, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.categoryFrameButton = QtWidgets.QPushButton(self.categoryFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoryFrameButton.sizePolicy().hasHeightForWidth())
        self.categoryFrameButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.categoryFrameButton.setFont(font)
        self.categoryFrameButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.categoryFrameButton.setIconSize(QtCore.QSize(20, 20))
        self.categoryFrameButton.setObjectName("categoryFrameButton")
        self.horizontalLayout_11.addWidget(self.categoryFrameButton)
        self.horizontalLayout_9.addWidget(self.categoryFrame2)
        self.verticalLayout_12.addWidget(self.categoryFrame)
        self.ctBodyFrame = QtWidgets.QFrame(self.scrollContentWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctBodyFrame.sizePolicy().hasHeightForWidth())
        self.ctBodyFrame.setSizePolicy(sizePolicy)
        self.ctBodyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ctBodyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ctBodyFrame.setObjectName("ctBodyFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.ctBodyFrame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ctFrame1 = QtWidgets.QFrame(self.ctBodyFrame)
        self.ctFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ctFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ctFrame1.setObjectName("ctFrame1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ctFrame1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.category1 = QtWidgets.QPushButton(self.ctFrame1)
        self.category1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/images/sofa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.category1.setIcon(icon3)
        self.category1.setObjectName("category1")
        self.gridLayout_3.addWidget(self.category1, 0, 0, 1, 1)
        self.categoryLabel1 = QtWidgets.QLabel(self.ctFrame1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.categoryLabel1.setFont(font)
        self.categoryLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.categoryLabel1.setObjectName("categoryLabel1")
        self.gridLayout_3.addWidget(self.categoryLabel1, 1, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.ctFrame1)
        self.ctFrame2 = QtWidgets.QFrame(self.ctBodyFrame)
        self.ctFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ctFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ctFrame2.setObjectName("ctFrame2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ctFrame2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.category2 = QtWidgets.QPushButton(self.ctFrame2)
        self.category2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/images/bedroom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.category2.setIcon(icon4)
        self.category2.setObjectName("category2")
        self.gridLayout_4.addWidget(self.category2, 0, 0, 1, 1)
        self.categoryLabel2 = QtWidgets.QLabel(self.ctFrame2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.categoryLabel2.setFont(font)
        self.categoryLabel2.setObjectName("categoryLabel2")
        self.gridLayout_4.addWidget(self.categoryLabel2, 1, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.ctFrame2)
        self.ctFrame3 = QtWidgets.QFrame(self.ctBodyFrame)
        self.ctFrame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ctFrame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ctFrame3.setObjectName("ctFrame3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ctFrame3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.category3 = QtWidgets.QPushButton(self.ctFrame3)
        self.category3.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/images/dinning-room.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.category3.setIcon(icon5)
        self.category3.setObjectName("category3")
        self.gridLayout_5.addWidget(self.category3, 0, 0, 1, 1)
        self.categoryLabel3 = QtWidgets.QLabel(self.ctFrame3)
        self.categoryLabel3.setObjectName("categoryLabel3")
        self.gridLayout_5.addWidget(self.categoryLabel3, 1, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.ctFrame3)
        self.ctFrame4 = QtWidgets.QFrame(self.ctBodyFrame)
        self.ctFrame4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ctFrame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ctFrame4.setObjectName("ctFrame4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.ctFrame4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.category4 = QtWidgets.QPushButton(self.ctFrame4)
        self.category4.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/images/office.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.category4.setIcon(icon6)
        self.category4.setObjectName("category4")
        self.gridLayout_6.addWidget(self.category4, 0, 0, 1, 1)
        self.categoryLabel4 = QtWidgets.QLabel(self.ctFrame4)
        self.categoryLabel4.setObjectName("categoryLabel4")
        self.gridLayout_6.addWidget(self.categoryLabel4, 1, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.ctFrame4)
        self.verticalLayout_12.addWidget(self.ctBodyFrame)
        self.ctBodyFrame2 = QtWidgets.QFrame(self.scrollContentWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctBodyFrame2.sizePolicy().hasHeightForWidth())
        self.ctBodyFrame2.setSizePolicy(sizePolicy)
        self.ctBodyFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ctBodyFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ctBodyFrame2.setObjectName("ctBodyFrame2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ctBodyFrame2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ctFrame5 = QtWidgets.QFrame(self.ctBodyFrame2)
        self.ctFrame5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ctFrame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ctFrame5.setObjectName("ctFrame5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ctFrame5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.category5 = QtWidgets.QPushButton(self.ctFrame5)
        self.category5.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/images/kitchen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.category5.setIcon(icon7)
        self.category5.setObjectName("category5")
        self.gridLayout_7.addWidget(self.category5, 0, 0, 1, 1)
        self.categoryLabel5 = QtWidgets.QLabel(self.ctFrame5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.categoryLabel5.setFont(font)
        self.categoryLabel5.setAlignment(QtCore.Qt.AlignCenter)
        self.categoryLabel5.setObjectName("categoryLabel5")
        self.gridLayout_7.addWidget(self.categoryLabel5, 1, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.ctFrame5)
        self.ctFrame6 = QtWidgets.QFrame(self.ctBodyFrame2)
        self.ctFrame6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ctFrame6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ctFrame6.setObjectName("ctFrame6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.ctFrame6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.category6 = QtWidgets.QPushButton(self.ctFrame6)
        self.category6.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/images/outdoor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.category6.setIcon(icon8)
        self.category6.setIconSize(QtCore.QSize(300, 300))
        self.category6.setObjectName("category6")
        self.gridLayout_8.addWidget(self.category6, 0, 0, 1, 1)
        self.categoryLabel6 = QtWidgets.QLabel(self.ctFrame6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.categoryLabel6.setFont(font)
        self.categoryLabel6.setAlignment(QtCore.Qt.AlignCenter)
        self.categoryLabel6.setObjectName("categoryLabel6")
        self.gridLayout_8.addWidget(self.categoryLabel6, 1, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.ctFrame6)
        self.ctFrame7 = QtWidgets.QFrame(self.ctBodyFrame2)
        self.ctFrame7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ctFrame7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ctFrame7.setObjectName("ctFrame7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.ctFrame7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.category7 = QtWidgets.QPushButton(self.ctFrame7)
        self.category7.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/images/decoration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.category7.setIcon(icon9)
        self.category7.setIconSize(QtCore.QSize(300, 300))
        self.category7.setObjectName("category7")
        self.gridLayout_9.addWidget(self.category7, 0, 0, 1, 1)
        self.categoryLabel7 = QtWidgets.QLabel(self.ctFrame7)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.categoryLabel7.setFont(font)
        self.categoryLabel7.setAlignment(QtCore.Qt.AlignCenter)
        self.categoryLabel7.setObjectName("categoryLabel7")
        self.gridLayout_9.addWidget(self.categoryLabel7, 1, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.ctFrame7)
        self.ctFrame8 = QtWidgets.QFrame(self.ctBodyFrame2)
        self.ctFrame8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ctFrame8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ctFrame8.setObjectName("ctFrame8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.ctFrame8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.category8 = QtWidgets.QPushButton(self.ctFrame8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category8.sizePolicy().hasHeightForWidth())
        self.category8.setSizePolicy(sizePolicy)
        self.category8.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/images/kids.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.category8.setIcon(icon10)
        self.category8.setIconSize(QtCore.QSize(300, 300))
        self.category8.setObjectName("category8")
        self.gridLayout_10.addWidget(self.category8, 0, 0, 1, 1)
        self.categoryLabel8 = QtWidgets.QLabel(self.ctFrame8)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.categoryLabel8.setFont(font)
        self.categoryLabel8.setAlignment(QtCore.Qt.AlignCenter)
        self.categoryLabel8.setObjectName("categoryLabel8")
        self.gridLayout_10.addWidget(self.categoryLabel8, 1, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.ctFrame8)
        self.verticalLayout_12.addWidget(self.ctBodyFrame2)
        self.scrollArea.setWidget(self.scrollContentWidget)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_6.addWidget(self.categoryWidget)
        self.emptyOrder = QtWidgets.QWidget(self.mainBody)
        self.emptyOrder.setObjectName("emptyOrder")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.emptyOrder)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.emptyOrder)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayout_6.addWidget(self.emptyOrder)
        self.verticalLayout.addWidget(self.mainBody)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchColumn.setPlaceholderText(_translate("MainWindow", "Search Chair, Table, Etc..."))
        self.categoryFrameLabel.setText(_translate("MainWindow", "Menu Category"))
        self.categoryFrameButton.setText(_translate("MainWindow", "All Product"))
        self.categoryLabel1.setText(_translate("MainWindow", "Living Room"))
        self.categoryLabel2.setText(_translate("MainWindow", "Bedroom"))
        self.categoryLabel3.setText(_translate("MainWindow", "Dinning Room"))
        self.categoryLabel4.setText(_translate("MainWindow", "Office"))
        self.categoryLabel5.setText(_translate("MainWindow", "Kitchen"))
        self.categoryLabel6.setText(_translate("MainWindow", "Outdoor"))
        self.categoryLabel7.setText(_translate("MainWindow", "Decoration"))
        self.categoryLabel8.setText(_translate("MainWindow", "Kids"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
