# /cashier_app/ui/order_item_ui.py
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_orderItemWidget(object):
    def setupUi(self, orderItemWidget):
        orderItemWidget.setObjectName("orderItemWidget")
        orderItemWidget.resize(344, 80)
        orderItemWidget.setStyleSheet("*{\n"
"    background-color:#ffffff;\n"
"}\n"
"\n"
"#btnMin,#btnPlus,#btnMin2,#btnPlus2,#delProduct,#delProduct2{\n"
"    border:transparent;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(orderItemWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(orderItemWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_8.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.imageCart = QtWidgets.QLabel(self.frame_10)
        self.imageCart.setMaximumSize(QtCore.QSize(40, 40))
        self.imageCart.setText("")
        self.imageCart.setPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/images/office chair.jpg"))
        self.imageCart.setScaledContents(True)
        self.imageCart.setObjectName("imageCart")
        self.horizontalLayout_8.addWidget(self.imageCart)
        self.nameCart3 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.nameCart3.setFont(font)
        self.nameCart3.setObjectName("nameCart3")
        self.horizontalLayout_8.addWidget(self.nameCart3)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(orderItemWidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_11 = QtWidgets.QFrame(self.frame_5)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnMin = QtWidgets.QToolButton(self.frame_11)
        self.btnMin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/icon/circle-minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMin.setIcon(icon)
        self.btnMin.setObjectName("btnMin")
        self.horizontalLayout_9.addWidget(self.btnMin)
        self.textNumber = QtWidgets.QLineEdit(self.frame_11)
        self.textNumber.setMaximumSize(QtCore.QSize(20, 20))
        self.textNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.textNumber.setObjectName("textNumber")
        self.horizontalLayout_9.addWidget(self.textNumber)
        self.btnPlus = QtWidgets.QToolButton(self.frame_11)
        self.btnPlus.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/icon/circle-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlus.setIcon(icon1)
        self.btnPlus.setObjectName("btnPlus")
        self.horizontalLayout_9.addWidget(self.btnPlus)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(orderItemWidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_13 = QtWidgets.QFrame(self.frame_6)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.priceCart = QtWidgets.QLabel(self.frame_13)
        self.priceCart.setAlignment(QtCore.Qt.AlignCenter)
        self.priceCart.setObjectName("priceCart")
        self.horizontalLayout_10.addWidget(self.priceCart)
        self.verticalLayout_4.addWidget(self.frame_13)
        self.horizontalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(orderItemWidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_15 = QtWidgets.QFrame(self.frame_7)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.delProduct = QtWidgets.QToolButton(self.frame_15)
        self.delProduct.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/icon/delete-trash-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delProduct.setIcon(icon2)
        self.delProduct.setObjectName("delProduct")
        self.horizontalLayout_11.addWidget(self.delProduct)
        self.verticalLayout_5.addWidget(self.frame_15)
        self.horizontalLayout.addWidget(self.frame_7)

        self.retranslateUi(orderItemWidget)
        QtCore.QMetaObject.connectSlotsByName(orderItemWidget)

    def retranslateUi(self, orderItemWidget):
        _translate = QtCore.QCoreApplication.translate
        orderItemWidget.setWindowTitle(_translate("orderItemWidget", "Form"))
        self.nameCart3.setText(_translate("orderItemWidget", "Wooden Chair"))
        self.textNumber.setText(_translate("orderItemWidget", "1"))
        self.priceCart.setText(_translate("orderItemWidget", "$19"))
