# /cashier_app/ui/order_detail_ui.py
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OrderDetailWidget(object):
    def setupUi(self, OrderDetailWidget):
        OrderDetailWidget.setObjectName("OrderDetailWidget")
        OrderDetailWidget.resize(407, 691)
        OrderDetailWidget.setStyleSheet("*{\n"
"    font-family:Segoe UI;\n"
"    background-color:#ffffff;\n"
"}\n"
"\n"
"#listRightMenu{\n"
"    background-color:white;\n"
"    border-left:1px solid #4b2e1d;\n"
"}\n"
"\n"
"#btnMin,#btnPlus,#btnMin2,#btnPlus2,#delProduct,#delProduct2{\n"
"    border:transparent;\n"
"}\n"
"\n"
"#clearCartButton,#tkButton,#deliveryButton{\n"
"    background-color: #212529;\n"
"    border-radius:5px;\n"
"    min-height:30px;\n"
"    color:#fff;\n"
"    font-size:15px;\n"
"    border:none;\n"
"    transition:0.2s ease;\n"
"}\n"
"\n"
"#clearCartButton:pressed,#tkButton:pressed,#deliveryButton:pressed{\n"
"     background-color: #495057;\n"
"}\n"
"\n"
"#orderButton{\n"
"    background-color:#212529;\n"
"    border-radius:5px;\n"
"    height:30px;\n"
"    color:white;\n"
"    border:none;\n"
"    transition:0.2s ease;\n"
"}\n"
"\n"
"#orderButton:pressed{\n"
"    background-color:#495057;\n"
"}\n"
"\n"
"#descBillsFrame{\n"
"    border-bottom:1px solid #dcdcdc;\n"
"    box-shadow:0px 4px 8px rgba(0,0,0,0.1);\n"
"}\n"
"\n"
"#pyIcon, #pyIcon2, #pyIcon3{\n"
"    border:1px solid #dcdcdc;\n"
"    background-color:#f9f9f9;\n"
"    border-radius:10px;\n"
"    font-size:12px;\n"
"    font-weight:bold;\n"
"    box-shadow:0px 4px 8px rgba(0,0,0,0.1);\n"
"    qproperty-iconSize:40px 40px;\n"
"    qproperty-toolButtonStyle:ToolButtonTextUnderIcon;\n"
"}\n"
"\n"
"#pyIcon:hover, #pyIcon2:hover, #pyIcon3:hover{\n"
"    background-color:#e0e0e0;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"#pyIcon:pressed, #pyIcon2:pressed, #pyIcon3:pressed{\n"
"    background-color:#c8c8c8c8;\n"
"    border-radius:5px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(OrderDetailWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.orderMenu = QtWidgets.QWidget(OrderDetailWidget)
        self.orderMenu.setStyleSheet("")
        self.orderMenu.setObjectName("orderMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.orderMenu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rightMenu = QtWidgets.QWidget(self.orderMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightMenu.sizePolicy().hasHeightForWidth())
        self.rightMenu.setSizePolicy(sizePolicy)
        self.rightMenu.setObjectName("rightMenu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightMenu)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.rightMenu)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Orderlabel = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Orderlabel.sizePolicy().hasHeightForWidth())
        self.Orderlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Orderlabel.setFont(font)
        self.Orderlabel.setObjectName("Orderlabel")
        self.horizontalLayout_5.addWidget(self.Orderlabel)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.rightMenu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.iconDate = QtWidgets.QLabel(self.frame_2)
        self.iconDate.setMaximumSize(QtCore.QSize(20, 20))
        self.iconDate.setText("")
        self.iconDate.setPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/icon/calendar-date-schedule.svg"))
        self.iconDate.setScaledContents(True)
        self.iconDate.setObjectName("iconDate")
        self.horizontalLayout_3.addWidget(self.iconDate)
        self.Date = QtWidgets.QLabel(self.frame_2)
        self.Date.setAlignment(QtCore.Qt.AlignCenter)
        self.Date.setObjectName("Date")
        self.horizontalLayout_3.addWidget(self.Date)
        self.dropDate = QtWidgets.QLabel(self.frame_2)
        self.dropDate.setMaximumSize(QtCore.QSize(20, 20))
        self.dropDate.setText("")
        self.dropDate.setPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/icon/dropdown-arrow.svg"))
        self.dropDate.setScaledContents(True)
        self.dropDate.setObjectName("dropDate")
        self.horizontalLayout_3.addWidget(self.dropDate)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.rightMenu)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.clearCartFrame = QtWidgets.QFrame(self.frame_3)
        self.clearCartFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clearCartFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clearCartFrame.setObjectName("clearCartFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.clearCartFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.clearCartButton = QtWidgets.QPushButton(self.clearCartFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.clearCartButton.setFont(font)
        self.clearCartButton.setObjectName("clearCartButton")
        self.gridLayout_5.addWidget(self.clearCartButton, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.clearCartFrame)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.rightMenu, 0, QtCore.Qt.AlignTop)
        self.rightMenu2 = QtWidgets.QWidget(self.orderMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightMenu2.sizePolicy().hasHeightForWidth())
        self.rightMenu2.setSizePolicy(sizePolicy)
        self.rightMenu2.setObjectName("rightMenu2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.rightMenu2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.rightMenu2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 389, 219))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_12 = QtWidgets.QFrame(self.widget)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_12)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.gridLayout_8.addWidget(self.frame_12, 0, 0, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.widget)
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_14)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.gridLayout_8.addWidget(self.frame_14, 0, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.widget)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.gridLayout_8.addWidget(self.frame_9, 0, 2, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.widget)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.gridLayout_8.addWidget(self.frame_8, 0, 3, 1, 1)
        self.gridLayout_9.addWidget(self.widget, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.cartItemContainer = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cartItemContainer.sizePolicy().hasHeightForWidth())
        self.cartItemContainer.setSizePolicy(sizePolicy)
        self.cartItemContainer.setObjectName("cartItemContainer")
        self.gridLayout_9.addWidget(self.cartItemContainer, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_6.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.rightMenu2)
        self.rightMenu3 = QtWidgets.QWidget(self.orderMenu)
        self.rightMenu3.setObjectName("rightMenu3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.rightMenu3)
        self.gridLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.rightMenu3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        self.frame_29 = QtWidgets.QFrame(self.rightMenu3)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_12.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.deliveryButton = QtWidgets.QPushButton(self.frame_29)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.deliveryButton.setFont(font)
        self.deliveryButton.setObjectName("deliveryButton")
        self.horizontalLayout_12.addWidget(self.deliveryButton)
        self.gridLayout_6.addWidget(self.frame_29, 1, 0, 1, 1)
        self.frame_24 = QtWidgets.QFrame(self.rightMenu3)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_20.setContentsMargins(-1, -1, 9, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.tkButton = QtWidgets.QPushButton(self.frame_24)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.tkButton.setFont(font)
        self.tkButton.setObjectName("tkButton")
        self.horizontalLayout_20.addWidget(self.tkButton)
        self.gridLayout_6.addWidget(self.frame_24, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.rightMenu3)
        self.rightMenu4 = QtWidgets.QWidget(self.orderMenu)
        self.rightMenu4.setObjectName("rightMenu4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.rightMenu4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.descBillsFrame = QtWidgets.QFrame(self.rightMenu4)
        self.descBillsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descBillsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.descBillsFrame.setObjectName("descBillsFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.descBillsFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_18 = QtWidgets.QFrame(self.descBillsFrame)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_2.setContentsMargins(0, 0, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_110 = QtWidgets.QLabel(self.frame_18)
        self.label_110.setObjectName("label_110")
        self.gridLayout_2.addWidget(self.label_110, 2, 1, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.gridLayout_2.addWidget(self.label_100, 0, 0, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_102.setFont(font)
        self.label_102.setObjectName("label_102")
        self.gridLayout_2.addWidget(self.label_102, 2, 0, 1, 1)
        self.label_111 = QtWidgets.QLabel(self.frame_18)
        self.label_111.setObjectName("label_111")
        self.gridLayout_2.addWidget(self.label_111, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_18)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_18)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_18, 0, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.descBillsFrame)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.subTotal = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.subTotal.setFont(font)
        self.subTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.subTotal.setObjectName("subTotal")
        self.verticalLayout_11.addWidget(self.subTotal)
        self.label_12 = QtWidgets.QLabel(self.frame_19)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.prDiscount = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.prDiscount.setFont(font)
        self.prDiscount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prDiscount.setObjectName("prDiscount")
        self.verticalLayout_11.addWidget(self.prDiscount)
        self.gridLayout.addWidget(self.frame_19, 0, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.descBillsFrame)
        self.frame_17 = QtWidgets.QFrame(self.rightMenu4)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_20 = QtWidgets.QFrame(self.frame_17)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_15.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_9 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_15.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_20)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_15.addWidget(self.label_10)
        self.gridLayout_3.addWidget(self.frame_20, 0, 0, 1, 1)
        self.frame_21 = QtWidgets.QFrame(self.frame_17)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.totalPrice = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.totalPrice.setFont(font)
        self.totalPrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalPrice.setObjectName("totalPrice")
        self.horizontalLayout_13.addWidget(self.totalPrice)
        self.gridLayout_3.addWidget(self.frame_21, 0, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.frame_17)
        self.verticalLayout.addWidget(self.rightMenu4)
        self.rightMenu5 = QtWidgets.QWidget(self.orderMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightMenu5.sizePolicy().hasHeightForWidth())
        self.rightMenu5.setSizePolicy(sizePolicy)
        self.rightMenu5.setObjectName("rightMenu5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.rightMenu5)
        self.verticalLayout_12.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.rightMenu5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.frame_22 = QtWidgets.QFrame(self.rightMenu5)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_22)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.py1 = QtWidgets.QFrame(self.frame_22)
        self.py1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.py1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.py1.setObjectName("py1")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.py1)
        self.gridLayout_40.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.pyIcon = QtWidgets.QToolButton(self.py1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pyIcon.sizePolicy().hasHeightForWidth())
        self.pyIcon.setSizePolicy(sizePolicy)
        self.pyIcon.setMinimumSize(QtCore.QSize(0, 0))
        self.pyIcon.setMaximumSize(QtCore.QSize(16777215, 70))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/icon/cash-svgrepo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pyIcon.setIcon(icon)
        self.pyIcon.setAutoRaise(False)
        self.pyIcon.setObjectName("pyIcon")
        self.gridLayout_40.addWidget(self.pyIcon, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.py1, 0, 0, 1, 1)
        self.py2 = QtWidgets.QFrame(self.frame_22)
        self.py2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.py2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.py2.setObjectName("py2")
        self.gridLayout_65 = QtWidgets.QGridLayout(self.py2)
        self.gridLayout_65.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout_65.setObjectName("gridLayout_65")
        self.pyIcon2 = QtWidgets.QToolButton(self.py2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pyIcon2.sizePolicy().hasHeightForWidth())
        self.pyIcon2.setSizePolicy(sizePolicy)
        self.pyIcon2.setMinimumSize(QtCore.QSize(0, 0))
        self.pyIcon2.setMaximumSize(QtCore.QSize(16777215, 70))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/icon/credit-card.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pyIcon2.setIcon(icon1)
        self.pyIcon2.setObjectName("pyIcon2")
        self.gridLayout_65.addWidget(self.pyIcon2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.py2, 0, 1, 1, 1)
        self.py3 = QtWidgets.QFrame(self.frame_22)
        self.py3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.py3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.py3.setObjectName("py3")
        self.gridLayout_66 = QtWidgets.QGridLayout(self.py3)
        self.gridLayout_66.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout_66.setObjectName("gridLayout_66")
        self.pyIcon3 = QtWidgets.QToolButton(self.py3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pyIcon3.sizePolicy().hasHeightForWidth())
        self.pyIcon3.setSizePolicy(sizePolicy)
        self.pyIcon3.setMinimumSize(QtCore.QSize(0, 0))
        self.pyIcon3.setMaximumSize(QtCore.QSize(16777215, 70))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../PyhtonTraining/cashier_app/PyQt/icon/qr-code-scan.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pyIcon3.setIcon(icon2)
        self.pyIcon3.setObjectName("pyIcon3")
        self.gridLayout_66.addWidget(self.pyIcon3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.py3, 0, 2, 1, 1)
        self.verticalLayout_12.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.rightMenu5)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_17.setContentsMargins(9, 0, -1, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.orderButton = QtWidgets.QPushButton(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderButton.sizePolicy().hasHeightForWidth())
        self.orderButton.setSizePolicy(sizePolicy)
        self.orderButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.orderButton.setFont(font)
        self.orderButton.setObjectName("orderButton")
        self.horizontalLayout_17.addWidget(self.orderButton)
        self.verticalLayout_12.addWidget(self.frame_23)
        self.verticalLayout.addWidget(self.rightMenu5)
        self.verticalLayout_2.addWidget(self.orderMenu)

        self.retranslateUi(OrderDetailWidget)
        QtCore.QMetaObject.connectSlotsByName(OrderDetailWidget)

    def retranslateUi(self, OrderDetailWidget):
        _translate = QtCore.QCoreApplication.translate
        OrderDetailWidget.setWindowTitle(_translate("OrderDetailWidget", "Form"))
        self.Orderlabel.setText(_translate("OrderDetailWidget", "Order Details"))
        self.Date.setText(_translate("OrderDetailWidget", "06/28/2025"))
        self.clearCartButton.setText(_translate("OrderDetailWidget", "Clear Cart"))
        self.label_4.setText(_translate("OrderDetailWidget", "Product"))
        self.label_5.setText(_translate("OrderDetailWidget", "Price"))
        self.label_3.setText(_translate("OrderDetailWidget", "QTY"))
        self.label_2.setText(_translate("OrderDetailWidget", "Delete"))
        self.label_8.setText(_translate("OrderDetailWidget", "Delivery Method"))
        self.deliveryButton.setText(_translate("OrderDetailWidget", "Delivery"))
        self.tkButton.setText(_translate("OrderDetailWidget", "Take Away"))
        self.label_110.setText(_translate("OrderDetailWidget", ":"))
        self.label_100.setText(_translate("OrderDetailWidget", "Sub Total"))
        self.label_102.setText(_translate("OrderDetailWidget", "Discount"))
        self.label_111.setText(_translate("OrderDetailWidget", ":"))
        self.label_7.setText(_translate("OrderDetailWidget", "Shpping"))
        self.label_11.setText(_translate("OrderDetailWidget", ":"))
        self.subTotal.setText(_translate("OrderDetailWidget", "$39"))
        self.label_12.setText(_translate("OrderDetailWidget", "Free"))
        self.prDiscount.setText(_translate("OrderDetailWidget", "$2"))
        self.label_9.setText(_translate("OrderDetailWidget", "Total"))
        self.label_10.setText(_translate("OrderDetailWidget", ":"))
        self.totalPrice.setText(_translate("OrderDetailWidget", "$37"))
        self.label_6.setText(_translate("OrderDetailWidget", "Payment Method"))
        self.pyIcon.setText(_translate("OrderDetailWidget", "Cash"))
        self.pyIcon2.setText(_translate("OrderDetailWidget", "Cart"))
        self.pyIcon3.setText(_translate("OrderDetailWidget", "E-Wallet"))
        self.orderButton.setText(_translate("OrderDetailWidget", "Order Now"))
