# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup_delivery.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(259, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("#widget{\n"
"    font-family:Segoe UI;\n"
"    color:#222222;\n"
"    background:rgba(250, 249, 248, 1);\n"
"}\n"
"\n"
"#frame{\n"
"    background-color:#fff;\n"
"    border-bottom:1px solid #dcdcdc;\n"
"    box-shadow:0px 4px 8px rgba(40, 29, 21, 1);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame)
        self.csNameLabel = QtWidgets.QLineEdit(self.widget)
        self.csNameLabel.setObjectName("csNameLabel")
        self.verticalLayout_2.addWidget(self.csNameLabel)
        self.addressLabel = QtWidgets.QLineEdit(self.widget)
        self.addressLabel.setObjectName("addressLabel")
        self.verticalLayout_2.addWidget(self.addressLabel)
        self.pnLabel = QtWidgets.QLineEdit(self.widget)
        self.pnLabel.setObjectName("pnLabel")
        self.verticalLayout_2.addWidget(self.pnLabel)
        self.noteLabel = QtWidgets.QLineEdit(self.widget)
        self.noteLabel.setObjectName("noteLabel")
        self.verticalLayout_2.addWidget(self.noteLabel)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveButton = QtWidgets.QPushButton(self.frame_2)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.resetButton = QtWidgets.QPushButton(self.frame_2)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Delivery Detail"))
        self.csNameLabel.setPlaceholderText(_translate("Dialog", "Customer Name"))
        self.addressLabel.setPlaceholderText(_translate("Dialog", "Address"))
        self.pnLabel.setPlaceholderText(_translate("Dialog", "Phone Number"))
        self.noteLabel.setPlaceholderText(_translate("Dialog", "Note"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.resetButton.setText(_translate("Dialog", "Reset"))
